export const staticPath = "static/"
export const indexFilePath = ".index/"
export const rssFilePath = "rss.xml"
export const rssResourcePath = ".rss_resources/"
export const indexHTMLPath = "index.html"
export const countHTMLPath = "count.html"
export const backupFilePath = "backup.json"
